### ISSUE TITLE
Study development using GDK by 4/14/16

### ISSUE THREAD

**Issue by adurso0747** [anthonyzayas/Emotion-Tracker#10]
https://www.youtube.com/watch?v=dTYRtbP5xkg

This series has a thorough overview of programming for glass. I think we should all try to watch all the way through this series and see what we can learn. When you finish the series please post a comment on what you learned. Also I think it would be good for us all to write a simple app in GDK. Something simple like a Hello world app.
- [ ] Explain what you learned
- [ ] Hello World app

**Comment by anthonyzayas** [comment]
Very relevant from Lectures 2 - 4, we can ignore the first because it deals with websites, not android. Good job finding it

**Comment by anthonyzayas** [comment]
In regards to this timeline, I believe this is not something we can have due so soon since we could only actively go through it during class. This event should be after we understand Android Studio and the Google API.

**Comment by anthonyzayas** [comment]
https://www.toptal.com/google-glass/building-your-first-glass-app-a-tutorial-for-aspiring-google-glass-developers - Here is an additional guide on google glass
